"""SQLAlchemy declarative base.

`Base` carries a constraint/index naming convention so any future
autogenerated migration emits deterministic, readable names (the M1–M5
migrations were hand-written, so this is inert for them — it only shapes
DDL that SQLAlchemy itself generates).
"""
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic names for constraints/indexes generated by SQLAlchemy.
NAMING_CONVENTION = {
    "ix": "%(column_0_label)s_idx",
    "uq": "%(table_name)s_%(column_0_name)s_key",
    "ck": "%(table_name)s_%(constraint_name)s_check",
    "fk": "%(table_name)s_%(column_0_name)s_fkey",
    "pk": "%(table_name)s_pkey",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Reusable created_at/updated_at columns for future models.

    The M1–M5 tables predate this mixin and declare their own
    `created_at`; new entities should mix this in instead.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), onupdate=func.now(), nullable=True
    )
